### ISSUE TITLE
not building

### ISSUE THREAD

**Issue by kaese77** [weimarnetz/firmware#2]
Configuring hostapd-mini.
Configuring olsrd-mod-watchdog.
Configuring olsrd-mod-arprefresh.
Configuring luci-i18n-freifunk-en.
Configuring kmod-usb-ledtrig-usbport.
Configuring luci-i18n-base-de.
Configuring rpcd-mod-iwinfo.
Configuring luci-i18n-base-en.
Configuring uhttpd-mod-ubus.
Configuring kmod-ipt-offload.
Configuring kmod-ipt-nat.
Collected errors:
 * check_conflicts_for: The following packages conflict with wpad-basic:
 * check_conflicts_for:         hostapd-mini *
 * opkg_install_cmd: Cannot install package wpad-basic.
Makefile:149: recipe for target 'package_install' failed
make[3]: *** [package_install] Error 255
Makefile:108: recipe for target '_call_image' failed
make[2]: *** [_call_image] Error 2
Makefile:192: recipe for target 'image' failed
make[1]: *** [image] Error 2

**Comment by kaese77** [comment]
openwrt-1806 und ar71xx

**Comment by mtippmann** [comment]
fixed in https://github.com/weimarnetz/firmware/commit/a46def7e8e579448d3f337d09dee3a5d493efdd2
