### ISSUE TITLE
Idee für Verkürzung Buildzeiten

### ISSUE THREAD

**Issue by andibraeu** [weimarnetz/firmware#21]
1. Aus dem Firmwarerepository werden keine Images mehr gebaut
2. Aus dem Fimwarerepository entsteht bei Änderungen nur noch ein Imagebuilder und ein SDK
3. beide Files werden auf den Fileserver hochgeladen
4. Im Package Repository reagieren wir auf Änderungen und bauen auf Basis der in 3. hochgeladenen Files die Images

Wir bauen dann nur noch das gesamte OpenWRT, wenn sich Änderungen daran ergeben

**Comment by mtippmann** [comment]
- openwrt-sdk entpacken: 

- im entpackten ordner die `feeds.conf` anpassen: 

dann: 

     $ ./scripts/feeds update -a 
     $ ./scripts/feeds install -a 

feeds.conf: 

     $ cat << EOF >> feeds.conf 
     src-git packages_weimar git://github.com/weimarnetz/packages.git^9a0222404a6eae94118abe9385cfc1c1414d2ea4
     EOF 

dann *müsste* es klappen mit 

    $ make package/weimarnetz-ffwizard/compile
    $ make package/vtun/compile

die die .ipk liegen dann in bin - das kann man auch mit rsync irgendwo hinschieben und als feed für den imagebuilder nutzen

**Comment by SvenRoederer** [comment]
Für die Berliner-Firmware hab ich auch schon mal solche Überlegungen angestellt. Eines der Probleme die mir aufgefallen sind: 
* die Zuordnung der Build-version: Bei getrenntem Bauen ist keine eingeutige Zuordnung vom Repo-build zum packages-build mehr möglich. Aktuell ergibt sich ja aus dem commit des Firmware-repos automatisch der verwendete packages-commit.

**Comment by andibraeu** [comment]
Unser Plan ist, unser eigenes Package Repo nicht mit im Firmware Repo zu bauen. Am Ende wird das Package Repo zum führenden Repo für die Images. Die Änderungen an unseren Packages verlangen im allgemeinen keinen neuen Build von OpenWrt.
Weiterhin planen wir, dass ein erfolgreicher Build von SDK und Image Builder einen Tag oder Commit auf dem Package Repo setzt, das dann die Images neu baut. Somit wären die verwendeten Versionen im Git dokumentiert

**Comment by SvenRoederer** [comment]
> Am Ende wird das Package Repo zum führenden Repo für die Images

Interessante Idee ...

**Comment by andibraeu** [comment]
es ist angerichtet...

**Comment by SvenRoederer** [comment]
Wie ist denn nun der Plan, "SDK + Imagebuilder selbst bauen" oder #325?

**Comment by andibraeu** [comment]
wir bauen imagebuilder + sdk selbst... 

1. hier aus diesem Repo bauen wir ib + sdk für verschiedene OpenWrt Releases
2. in https://github.com/weimarnetz/packages/actions werden dann konkrete Images + unsere Packages draus, die auf unserem build-server landen

Bedeutet: Wenn wir nur etwas an unseren Packages ändern haben wir in 30-40 Minuten neue Images für 2 OpenWrt-Versionen und alle bei uns definierten Geräte

**Comment by SvenRoederer** [comment]
D.h.: 
* kernel, toolchain, Tools und Targets könnt ihr via patches beeinflussen (z.B: backport von Geräten aus OpenWrt-master nach OpenWrt-21.02)
* patches für OpenWrt-core packages (http://lists.openwrt.org/pipermail/openwrt-devel/2021-May/035207.html) die aus Gründen (tm) nicht gemerged sind gehen via Imagebuilder in die packages
* patches for packages von anderen Feeds könnt ihr auch via Imagebuilder einbauen

Wenn dann SDK und Imagebuilder fertig sind richtet ihr im SDK nur euren Feed ein und baut dessen packages. Das erklärt den Berg an Meldungen über nicht gefundenen Abhängigkeiten. Und da hab ich jetzt 2 Fragen:
* Wenn das SDK die Abhängigkeiten nicht findet, baut es die pakete trotzdem (ohne Zauberei)? Für die LuCI-apps, die ja nur "Plugins" sind und an die richtige Stelle Kopiert werden müssen, scheint das zu klappen.
* Das `vtun` binary benötigt liblzo, libz und openssl ... wie könnt ihr das bauen, ohne die Libraries vorher zu bauen?

**Comment by mtippmann** [comment]
@SvenRoederer wir bauen nur ein paar pakete mit dem sdk momentan, die fehlermeldungen scheinen keine rolle zu spielen und es funktioniert trotzdem. `vtun` wird ohne lzo, libz und openssl gebaut - die makefile ist da etwas unschön, deswegen klappt das auch.

**Comment by mtippmann** [comment]
@SvenRoederer konkret definieren wir die optionen, dass die abhängigkeiten nicht benötigt werden: https://github.com/weimarnetz/packages/blob/brauhaus-19.07/net/vtun/Makefile#L20  - das sdk warnt trotzdem, luci-apps spucken auch viele warnungen aus, aber der build sollte da nur im kopieren bestehen und deswegen klappt das, mit anderen optionen geht das vermutlich auch schief.
