### ISSUE TITLE
Frontend Fehler bei Klick auf "Freifunk"

### ISSUE THREAD

**Issue by andibraeu** [weimarnetz/firmware#22]
Meldung von Christfried:

1) Wenn ich links oben auf "Freifunk" klicke, dann kommt:

```  /usr/lib/lua/luci/dispatcher.lua:1195: attempt to index local 'f' (a nil value)
  stack traceback:
  	/usr/lib/lua/luci/dispatcher.lua:1195: in function 'createtree_json'
 	/usr/lib/lua/luci/dispatcher.lua:703: in function 'menu_json'
  	/usr/lib/lua/luci/dispatcher.lua:796: in function 'dispatch'
  	/usr/lib/lua/luci/dispatcher.lua:1000: in function 'dispatch'
  	/usr/lib/lua/luci/dispatcher.lua:479: in function </usr/lib/lua/luci/dispatcher.lua:478>
```
Danach geht es nicht weiter.

**Comment by bobidle** [comment]
@andibraeu das Problem tritt laut dem Reporter nicht mehr auf.

Kannst du diesen Bug noch in einer aktuellen Firmware Installation reproduzieren?

**Comment by andibraeu** [comment]
genau dieses problem wird nicht mehr auftreten, da wir lua aus dem frontend rausoperiert haben

**Comment by bobidle** [comment]
Okay, dann kann das Issue geschlossen werden?
