### ISSUE TITLE
no 11s 5ghz mesh with ath10k-ct 

### ISSUE THREAD

**Issue by mtippmann** [weimarnetz/firmware#7]
it's not supported: 

```
2.4 no problems: 
valid interface combinations:
                 * #{ managed } <= 2048, #{ AP, mesh point } <= 8, #{ P2P-client, P2P-GO } <= 1, #{ IBSS } <= 1,
                   total <= 2048, #channels <= 1, STA/AP BI must match, radar detect widths: { 20 MHz (no HT), 20 MHz, 40 MHz }

5ghz: 

            * #{ managed, P2P-client } <= 16, #{ P2P-GO } <= 3, #{ AP } <= 16, #{ IBSS } <= 1,
                   total <= 16, #channels <= 1, STA/AP BI must match, radar detect widths: { 20 MHz (no HT), 20 MHz, 40 MHz, 80 MHz, 80+80 MHz, 160 MHz }
```

**Comment by andibraeu** [comment]
und was machen wir da?

welche geräte betrifft das?

**Comment by mtippmann** [comment]
siehe hier für eine ausführliche diskussion: https://github.com/FreifunkFranken/firmware/commit/aca1223f069750c1d9cca4ec952fae3e338dc590

wir müssten uns an das berliner buildsystem anpassen - das betrifft alle 5ghz ac wave1 geräte - größtenteils tp-link archer geräte.

**Comment by mtippmann** [comment]
soweit ich die diskussion in den links jetzt verfolgt habe: es wäre okay weiterhin kmod-ath10k-ct zu nutzen (das hat noch einige patches zusätzlich zu ath10k und wohl auch hacks für weniger ram-verbrauch) - und als firmware könnten wir die reguläre ath10k-firmware nutzen (ohne die -ct variante) - allerdings bin ich nicht ganz sicher ob wir dann kmod-ath10k-ct nicht auch noch patchen müssen, weil die validen interface-kombinationen ap+11s mesh nicht unterstützen.

**Comment by mtippmann** [comment]
also wave2 geräte sind davon wohl nicht betroffen d.h. wir bräuchten "nur" die firmware für ath10k wave1 geräte austauschen (falls das dann klappt) - irgendwo findet sich sicherlich eine liste der wave1 geräte - wave1/2 ist hier erklärt: https://www.heise.de/ix/heft/Perfekte-Welle-2822771.html vermutlich haben wir fast nur wave1 geräte - also hilft uns der support für wave2 geräte nicht so viel momentan :(

**Comment by andibraeu** [comment]
gibt es wave1-Geräte, für die wir noch keine Firmware mit OpenWrt 18.06 haben?

**Comment by andibraeu** [comment]
es ist angerichtet.. siehe https://github.com/weimarnetz/packages/commit/84e11c1b7b357742df57e4c7f166dd6a51325e2e und einiges dazwischen und https://github.com/weimarnetz/packages/commit/f2cad865b2bcfc6fd700883c3316214b61e5e543 sowie https://github.com/weimarnetz/firmware/commit/4f1ab739d004695814e12c364f19837f37c29539

**Comment by andibraeu** [comment]
jetzt müssen wir es nur noch testen

**Comment by SvenRoederer** [comment]
So eine Idee hatte ich auch, war aber nicht wirklich begeistert noch einen Satz parameter zu pflegen (packagelists, profiles und dann auch noch geräte spezifische treiber) 
Der Spalter-Weg, alle Treiber-versionen ins Image packen und zur Laufzeit den passenden auswählen ist das andere extrem ...

Ich hatte mal die einer Abwandlung von Gluon gespielt, da kann man "alias"-Treiber definieren, die dann das Ganze "+" und "-" managen. Und man kann auch "aliase" für anderes definieren (olsr, webUI, network-tools, ...). Aber die nötige Zeit ........

**Comment by akira25** [comment]
@SvenRoederer Das ist so nicht richtig! Wir packen standardmäßig für alle Geräte mit ath10k-ct Treiber und nur die Wave1-Geräte mit dem nicht-standard ath10k-Treiber. Unser Buildsystem erkennt automatisch, ob ein ath10k-Gerät vorliegt und manipultiert die Paketliste entsprechend nur für dieses eine Image.

Da Adhoc eh veraltet ist, nehmen wir in kauf, dass Wave1-Geräte dann kein Adhoc mehr können. Schafft auch nen Anreiz auf 11s zu wechseln.

Das wir sinnlos beide Treiber gleichzeitig installierten ist quatsch. Das verhindert übrigens auch OpenWrt von Haus aus. Entweder oder. Aber beides zusammen geht nicht.

**Comment by akira25** [comment]
Falls Interesse an jenem Code besteht, findet man diesen hier:
https://github.com/Freifunk-Spalter/builter/pull/44/files

**Comment by andibraeu** [comment]
Ich hab es lieber expliziter, und die Lösung erlaubt uns dann auch andere Paketkonfigurationen pro Gerät festzulegen

**Comment by andibraeu** [comment]
aber ich habe eure Mechanik benutzt, die wave1-Geräte zu identifizieren, weil ich sonst nirgends eine Liste finden konnte @Akira25

**Comment by SvenRoederer** [comment]
@Akira25 Als ich letztens bei euch reingesehen hab, stand "alle Treiber ins image packen und zur Laufzeit installieren" im Raum. Schön dass ihr da eine effektivere Lösung gefunden habt.

https://github.com/freifunk-gluon/gluon/blob/edff676de9e7e7022c3618ab31545883ec9e23d2/targets/ath79-generic hat auch eine Liste der Chipsets, die sich jedenfalls deckt und die Auflistung der betroffenen Chipsets war ja ursprünglich auch nicht ganz klar.

**Comment by andibraeu** [comment]
ich glaub, das läuft jetzt 👯
