### ISSUE TITLE
luci webinterface wants to reconfigure wifi

### ISSUE THREAD

**Issue by andibraeu** [weimarnetz/firmware#8]
Reconfiguring wifi destroys our custom configuration and the router won't work as expected anymore

![image](https://user-images.githubusercontent.com/1162168/82752888-90b12980-9dc1-11ea-842f-24e449d44fff.png)

**Comment by mtippmann** [comment]
hmm, könnte man an der wurzel packen und gleich was konformes bauen? ich finde dazu hier überhaupt nichts: https://openwrt.org/docs/guide-user/network/wifi/basic 

der scheint `config wifi-iface` in `config wifi-iface wifinet1` umzubennen? eventuell hat das irgendwelche auswirkungen auf andere scripte? 

ich schau mal was genau passiert.

**Comment by SvenRoederer** [comment]
folgende infos haben wir dazu in der Berliner Firmware ... https://github.com/freifunk-berlin/firmware/issues/745

Aber auch noch keine Lösung ...

**Comment by andibraeu** [comment]
cool, danke! :)

**Comment by andibraeu** [comment]
@SvenRoederer ich hab einfach mal named sections bei uns eingebaut, auf unsere scripts sollte das keinen einfluss haben, jedenfalls wird wifi-iface nirgends bei uns direkt referenziert

**Comment by SvenRoederer** [comment]
ich vermute bei uns wirde das auch so klappen, muss nur mal jemand schreiben und testen ...
