### ISSUE TITLE
OLSR ether-mode analysieren

### ISSUE THREAD

**Issue by andibraeu** [weimarnetz/firmware#9]
Im DNT haben wir 4 Nanostations, die über einen 841 per Kabel miteinander verbunden sind. Durch "Option 'ether' 1" sollten die LAN-Verbindungen eigentlich mit 0,1 in die ETX-Rechnung einfließen. Das passiert im DNT nicht.

Mögliche Ursachen:
* der Switch läuft noch mit einer alten Version (Chaos Calmer, ...)
* der ether-mode läuft nicht mehr in neueren OLSR-Versionen?

Um das nachzustellen nehme man 2 Router und verbinde sie über die Ethernetports per Kabel. Erwartetes Ergebnis: In der Nachbartabelle von OLSR sollen der ETX-Wert für diese Verbindung bei 0,1 liegen

**Comment by koleesch** [comment]
Testkonstellation:
841er mit 19.07 v1.18 an 842er mit 18.06 per lan verbunden, dazu ein  TL-MR3420 v2 mit 18.06 (brauhaus-100+openwrt-r6907+989-7e15e21766) per wlan mesh

ergebnis
Local       Remote       vTime  LQ            NLQ         Cost        Host 
...            ...                136092 1.000000 0.897000 1.113281 842er per lan verbunden 
...            ...                138595 0.804000 0.851000 1.460938 mesh per wlan

**Comment by andibraeu** [comment]
interessant... sind die router noch im weimarnetz, kann man sich mal darauf verbinden?

**Comment by andibraeu** [comment]
und kannst du vielleicht alle router mit einer 19.07er Firmware versorgen?

**Comment by koleesch** [comment]
> interessant... sind die router noch im weimarnetz, kann man sich mal darauf verbinden?

830 und 34

**Comment by mtippmann** [comment]
19.07 841nv11 mac1200r sieht gut aus: 

vom 841n: 
```
10.63.12.161 10.63.55.225 142369 1.000000 1.000000 0.099609 mid1.ffweimar-hybrid-dhcp-820.olsr 
```

und vom mac1200r: 

```
10.63.55.225 10.63.12.161 137279 1.000000 1.000000 0.099609 balkonien.olsr 
```

**Comment by mtippmann** [comment]
eventuell ist das linkmult-plugin schuld? das fehlt bei mir in 19.07

**Comment by andibraeu** [comment]
läuft, Probleme gibt es, wenn man von ar71xx zu ath79 wechselt und die Einstellungen beibehalten will

**Comment by SvenRoederer** [comment]
> läuft, Probleme gibt es, wenn man von ar71xx zu ath79 wechselt und die Einstellungen beibehalten will

welche einstellungen? die für Wifi?

**Comment by andibraeu** [comment]
Die settings für Ethernet und die Switch-config ändert sich. Da sind dann WAN und LAN anders konfiguriert und die MAC-Adressen neu verteilt. 

Openwrt empfiehlt bei einem Update von ar71xx zu ath79 auch, die alten Settings nicht zu übernehmen

**Comment by SvenRoederer** [comment]
Ja, das Problem ist nicht unbekannt. Teilweise gibt's Ansätze, igration-script zu machen, das ist aber eher selten perfekt in OpenWrt. Drum mache ich für die Berliner Firmware auch keine neuen Geräte mehr für ar71xx rein und nur noch für ath79 - das reduziert Umstellungsprobleme.
